services:
  - type: web
    name: minecraftme-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/test
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: CLIENT_URL
        value: https://minecraftme.vercel.app
      - key: CORS_ORIGIN
        value: https://minecraftme.vercel.app
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 30
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: LOG_LEVEL
        value: info 